### ISSUE TITLE
all probabilities become almost 1 while applying the model

### ISSUE THREAD

**Issue by AmNotGod** [danaitri/Face-detection-cnn#1]
Hi, I try to apply the model to my face detection project currently.  However,  I find that the output hot-map is almost all ones. The following is the step that I apply the model:
(1) use opencv to read a image.
(2) subtract the image with mean pixles in BGR form (104, 117, 123).
(3) forward the image through the net to get a face hot-map(the prob blob).
Is there something wrong with my steps?

**Comment by danaitri** [comment]
Hello!
First of all if you want to receive values in [0,100] and not in [0,1] you
should remove the softmax layer from the deploy prototxt. I am sending  you
the prototxt you should use and I will also update it on github.
Secondly, I am not performing step 2. In project, I am doing a forward pass
of the image without substracting the mean value.

Have a nice day!
Danai

**Comment by AmNotGod** [comment]
That is very helpful! Thank you so much!

**Comment by sunjunlishi** [comment]
forward之后是热图，然后要自己处理获得人脸框呀？
