### ISSUE TITLE
what's the actual speed of the pre-trainned model?

### ISSUE THREAD

**Issue by tornadomeet** [danaitri/Face-detection-cnn#2]
Hello, @danaitri 
thanks for providing the pre-trained model of your paper.
i just read your paper and found it only says the model has 6M FLOPS, not reported the fps, but how about the actual running speed? such as in 640*480, min-size=32, normal pc cpu(i7 4core)?  thanks~

**Comment by danaitri** [comment]
Hello Wei Wu,

On a mid range GPU the network is capable of processing 129 images of size
227 x 227 per second. A single forward pass of a 227 x 227 image takes
0.007749 seconds. This is without pyramid detection.

Have a nice day,
Danai

**Comment by inspirit** [comment]
Hello, I can't seem to find a link for the paper... Can you please share it?
thank you.

**Comment by tornadomeet** [comment]
@danaitri  great! thanks~
@inspirit  your can seach: A Fast Deep Convolutional Neural Network for Face Detection in Big Visual Data

**Comment by sunjunlishi** [comment]
怎么通过forward结果，获得 人脸矩形框呀

**Comment by sunjunlishi** [comment]
可以仿照mtcnn的网上开源的代码进行处理，很多
